name: Deploy Next.js to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_RPC_URL=${{ secrets.NEXT_PUBLIC_RPC_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_RPC_URL_DEV=${{ secrets.NEXT_PUBLIC_RPC_URL_DEV }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SOLANA_NETWORK=${{ secrets.NEXT_PUBLIC_SOLANA_NETWORK }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> $GITHUB_ENV
          echo "WEBSITE_URL=${{ secrets.WEBSITE_URL }}" >> $GITHUB_ENV
          echo "SECRET_ADDRESS=${{ secrets.SECRET_ADDRESS }}" >> $GITHUB_ENV
          echo "KV_URL=${{ secrets.KV_URL }}" >> $GITHUB_ENV
          echo "KV_REST_API_URL=${{ secrets.KV_REST_API_URL }}" >> $GITHUB_ENV
          echo "KV_REST_API_TOKEN=${{ secrets.KV_REST_API_TOKEN }}" >> $GITHUB_ENV
          echo "KV_REST_API_READ_ONLY_TOKEN=${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Verify build files
        run: |
          echo "Verifying build files"
          ls -alh .next
          ls -alh public
          ls -alh package.json
          ls -alh package-lock.json
          ls -alh next.config.mjs

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: |
            .next
            public
            package.json
            package-lock.json
            next.config.mjs
          target: /home/coingalaxy/front

      - name: SSH and restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/coingalaxy/front
            npm install --omit=dev
            pm2 restart nextjs || pm2 start npm --name "nextjs" -- start
            pm2 save
